<template>
  <div 
    class="report-template bg-white flex flex-col" 
    :class="orientation === 'landscape' ? 'h-[210mm] w-[297mm]' : 'h-[297mm] w-[210mm]'"
    :style="{
      boxSizing: 'border-box',
      padding: orientation === 'landscape' ? '5mm 8mm' : '8mm 5mm'
    }"
  >
    <!-- Report Header -->
    <div v-if="showHeader" class="report-header border-b-2 border-gray-800 pb-4 mb-4 flex-shrink-0">
      <div class="flex justify-between items-start">
        <div class="flex items-start gap-4 flex-1">
          <!-- Logo Area - Resizable -->
          <div 
            v-if="logoUrl" 
            :style="{ width: logoSize + 'px', height: logoSize + 'px' }"
            class="rounded-lg overflow-hidden flex items-center justify-center bg-white flex-shrink-0"
          >
            <img :src="logoUrl" alt="Company Logo" class="w-full h-full object-contain" />
          </div>
          <div 
            v-else
            :style="{ width: logoSize + 'px', height: logoSize + 'px' }"
            class="bg-blue-600 rounded-lg flex items-center justify-center cursor-pointer hover:bg-blue-700 transition-colors flex-shrink-0"
            @click="$emit('upload-logo')"
            title="Click to upload logo"
          >
            <svg class="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
            </svg>
          </div>
          <!-- Company Info beside logo -->
          <div class="flex-1">
            <h2 class="text-base font-bold text-gray-900">{{ companyName }}</h2>
            <p class="text-sm text-gray-600 mt-1 whitespace-pre-line">{{ companyAddress }}</p>
          </div>
        </div>
        <div class="text-right">
          <p class="text-xs text-gray-500 uppercase tracking-wide mb-1">Report Generated</p>
          <p class="text-sm font-semibold text-gray-900">{{ formatDate(generatedDate) }}</p>
          <p class="text-xs text-gray-600 mt-1">{{ formatTime(generatedDate) }}</p>
        </div>
      </div>
    </div>

    <!-- Report Title - Below header, above content -->
    <div v-if="showHeader" class="mb-4 flex-shrink-0">
      <div class="flex justify-between items-start gap-4">
        <div class="flex-1">
          <h1 class="text-xl font-bold text-gray-900">{{ title }}</h1>
          <p v-if="subtitle" class="text-sm text-gray-600 mt-1">{{ subtitle }}</p>
        </div>
        <div class="text-right flex-shrink-0">
          <p class="text-xs text-gray-500 uppercase tracking-wide mb-1">Reference No.</p>
          <p class="text-sm font-semibold text-gray-900 font-mono">{{ referenceNo }}</p>
          <p class="text-xs text-gray-600 mt-2">Generated by:</p>
          <p class="text-xs font-medium text-gray-900">{{ currentUsername || generatedBy }}</p>
        </div>
      </div>
    </div>

    <!-- Filters Applied Section (if any) -->
    <div v-if="appliedFilters.length > 0" class="mb-6 bg-blue-50 border border-blue-200 rounded-lg p-4 flex-shrink-0">
      <h3 class="text-xs font-semibold text-blue-900 uppercase tracking-wide mb-2">Filters Applied</h3>
      <div class="grid grid-cols-2 gap-x-6 gap-y-2">
        <div v-for="filter in appliedFilters" :key="filter.label" class="flex items-center gap-2">
          <span class="text-xs text-blue-700 font-medium">{{ filter.label }}:</span>
          <span class="text-xs text-blue-900">{{ filter.value }}</span>
        </div>
      </div>
    </div>

    <!-- No Data Message -->
    <div v-if="!hasData" class="flex justify-center items-center py-20">
      <div class="text-center">
        <svg class="w-24 h-24 mx-auto text-gray-300 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        <p class="text-lg font-medium text-gray-900 dark:text-white">No Report Data Available</p>
        <p class="text-sm text-gray-500 dark:text-gray-400 mt-2">Please adjust your filters and generate the report again.</p>
      </div>
    </div>

    <!-- Main Content Slot -->
    <div v-if="showTable && hasData" class="report-content flex-1" style="min-height: 0; overflow: hidden;">
      <slot></slot>
    </div>

    <!-- Summary Slot - Only show on last page -->
    <div v-if="$slots.summary && isLastPage" class="mt-4 mb-4 flex-shrink-0">
      <div class="bg-white p-4 max-w-xs">
        <h3 class="text-xs font-semibold text-gray-900 uppercase tracking-wide mb-3">Summary</h3>
        <slot name="summary"></slot>
      </div>
    </div>

    <!-- Report Footer -->
    <div 
      v-if="showFooter" 
      class="report-footer mt-auto border-t border-gray-300 flex-shrink-0"
      :class="orientation === 'landscape' ? 'pt-6 pb-2 px-4' : 'pt-4 px-4'"
    >
      <div class="flex justify-between items-center text-xs text-gray-600">
        <div>
          <p class="font-semibold text-gray-900">{{ companyName }}</p>
        </div>
        <div class="text-right">
          <p class="mt-0.5">Page {{ pageIndex + 1 }} of {{ totalPages }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import axios from '@/utils/axios'

interface SummaryCard {
  label: string
  value: string | number
  subtitle?: string
}

interface AppliedFilter {
  label: string
  value: string
}

const props = defineProps({
  title: {
    type: String,
    required: true
  },
  subtitle: {
    type: String,
    default: ''
  },
  orientation: {
    type: String as () => 'portrait' | 'landscape',
    default: 'portrait'
  },
  generatedDate: {
    type: Date,
    default: () => new Date()
  },
  appliedFilters: {
    type: Array as () => AppliedFilter[],
    default: () => []
  },
  summaryCards: {
    type: Array as () => SummaryCard[],
    default: () => []
  },
  companyName: {
    type: String,
    default: 'Warehouse Management System'
  },
  companyAddress: {
    type: String,
    default: 'Generated from WMS Platform'
  },
  generatedBy: {
    type: String,
    default: 'System Administrator'
  },
  logoUrl: {
    type: String,
    default: ''
  },
  logoSize: {
    type: Number,
    default: 80
  },
  showHeader: {
    type: Boolean,
    default: true
  },
  showTable: {
    type: Boolean,
    default: true
  },
  showFooter: {
    type: Boolean,
    default: true
  },
  referenceNo: {
    type: String,
    default: ''
  },
  hasData: {
    type: Boolean,
    default: true
  },
  pageIndex: {
    type: Number,
    default: 0
  },
  totalPages: {
    type: Number,
    default: 1
  }
})

defineEmits(['upload-logo'])

const currentUsername = ref('')

const isLastPage = computed(() => {
  return props.pageIndex === props.totalPages - 1
})

const formatDate = (date: Date) => {
  return date.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })
}

const formatTime = (date: Date) => {
  return date.toLocaleTimeString('en-US', { 
    hour: '2-digit', 
    minute: '2-digit',
    hour12: true
  })
}

const fetchCurrentUser = async () => {
  try {
    const userStr = localStorage.getItem('user')
    if (userStr) {
      const user = JSON.parse(userStr)
      if (user.username) {
        currentUsername.value = user.username
      } else if (user.name) {
        currentUsername.value = user.name
      }
    }
  } catch (error) {
    console.error('Error fetching current user:', error)
  }
}

onMounted(() => {
  fetchCurrentUser()
})
</script>

<style scoped>
.report-template {
  font-family: 'Inter', system-ui, -apple-system, sans-serif;
  line-height: 1.5;
  box-sizing: border-box;
}

/* Professional table styling */
.report-template :deep(table) {
  width: 100%;
  border-collapse: collapse;
  font-size: 12px;
}

.report-template :deep(thead) {
  background: #f9fafb;
  border-bottom: 2px solid #e5e7eb;
}

.report-template :deep(th) {
  padding: 8px 10px;
  text-align: left;
  font-weight: 600;
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #374151;
  border-bottom: 2px solid #d1d5db;
}

.report-template :deep(td) {
  padding: 8px 10px;
  color: #111827;
  border-bottom: 1px solid #e5e7eb;
  font-size: 11px;
}

.report-template :deep(tbody tr:hover) {
  background: #f9fafb;
}

.report-template :deep(tbody tr:last-child td) {
  border-bottom: 2px solid #d1d5db;
}

/* Status badges */
.report-template :deep(.status-badge) {
  display: inline-block;
  padding: 4px 10px;
  border-radius: 9999px;
  font-size: 11px;
  font-weight: 500;
}

/* Print styles */
@media print {
  .report-template {
    print-color-adjust: exact;
    -webkit-print-color-adjust: exact;
    page-break-after: always;
  }
  
  .report-template.h-\[297mm\] {
    height: 297mm !important;
    width: 210mm !important;
    padding: 8mm 5mm !important;
  }
  
  .report-template.h-\[210mm\] {
    height: 210mm !important;
    width: 297mm !important;
    padding: 5mm 8mm !important;
  }
  
  .report-header,
  .report-footer {
    flex-shrink: 0;
  }
  
  .report-content {
    flex: 1;
    min-height: 0;
  }
}
</style>
