<template>
  <div class="report-template bg-white">
    <!-- Report Header -->
    <div v-if="showHeader" class="report-header border-b-2 border-gray-800 pb-6 mb-6">
      <div class="flex justify-between items-start">
        <div class="flex-1">
          <div class="flex items-center gap-3 mb-2">
            <!-- Logo Area - Custom or Default -->
            <div 
              v-if="logoUrl" 
              class="w-12 h-12 rounded-lg overflow-hidden flex items-center justify-center bg-white "
            >
              <img :src="logoUrl" alt="Company Logo" class="w-full h-full object-contain" />
            </div>
            <div 
              v-else
              class="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center cursor-pointer hover:bg-blue-700 transition-colors"
              @click="$emit('upload-logo')"
              title="Click to upload logo"
            >
              <svg class="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
              </svg>
            </div>
            <div>
              <h1 class="text-2xl font-bold text-gray-900">{{ title }}</h1>
              <p class="text-sm text-gray-600 mt-0.5">{{ subtitle }}</p>
            </div>
          </div>
        </div>
        <div class="text-right">
          <p class="text-xs text-gray-500 uppercase tracking-wide mb-1">Report Generated</p>
          <p class="text-sm font-semibold text-gray-900">{{ formatDate(generatedDate) }}</p>
          <p class="text-xs text-gray-600 mt-1">{{ formatTime(generatedDate) }}</p>
        </div>
      </div>
    </div>

    <!-- Filters Applied Section (if any) -->
    <div v-if="appliedFilters.length > 0" class="mb-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
      <h3 class="text-xs font-semibold text-blue-900 uppercase tracking-wide mb-2">Filters Applied</h3>
      <div class="grid grid-cols-2 gap-x-6 gap-y-2">
        <div v-for="filter in appliedFilters" :key="filter.label" class="flex items-center gap-2">
          <span class="text-xs text-blue-700 font-medium">{{ filter.label }}:</span>
          <span class="text-xs text-blue-900">{{ filter.value }}</span>
        </div>
      </div>
    </div>

    <!-- Summary Cards (optional) -->
    <div v-if="summaryCards.length > 0" class="grid gap-4 mb-6" :class="`grid-cols-${summaryCards.length}`">
      <div
        v-for="card in summaryCards"
        :key="card.label"
        class="border border-gray-200 rounded-lg p-4"
      >
        <p class="text-xs text-gray-600 font-medium uppercase tracking-wide mb-1">{{ card.label }}</p>
        <p class="text-2xl font-bold text-gray-900">{{ card.value }}</p>
        <p v-if="card.subtitle" class="text-xs text-gray-500 mt-1">{{ card.subtitle }}</p>
      </div>
    </div>

    <!-- Main Content Slot -->
    <div v-if="showTable" class="report-content">
      <slot></slot>
    </div>

    <!-- Report Footer -->
    <div v-if="showFooter" class="report-footer mt-8 pt-4 border-t border-gray-300">
      <div class="flex justify-between items-center text-xs text-gray-600">
        <div>
          <p class="font-semibold text-gray-900">{{ companyName }}</p>
          <p class="mt-0.5">{{ companyAddress }}</p>
        </div>
        <div class="text-right">
          <p>Generated by: <span class="font-medium text-gray-900">{{ generatedBy }}</span></p>
          <p class="mt-0.5">Page 1 of 1</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { defineProps } from 'vue'

interface SummaryCard {
  label: string
  value: string | number
  subtitle?: string
}

interface AppliedFilter {
  label: string
  value: string
}

const props = defineProps({
  title: {
    type: String,
    required: true
  },
  subtitle: {
    type: String,
    default: ''
  },
  generatedDate: {
    type: Date,
    default: () => new Date()
  },
  appliedFilters: {
    type: Array as () => AppliedFilter[],
    default: () => []
  },
  summaryCards: {
    type: Array as () => SummaryCard[],
    default: () => []
  },
  companyName: {
    type: String,
    default: 'Warehouse Management System'
  },
  companyAddress: {
    type: String,
    default: 'Generated from WMS Platform'
  },
  generatedBy: {
    type: String,
    default: 'System Administrator'
  },
  logoUrl: {
    type: String,
    default: ''
  },
  showHeader: {
    type: Boolean,
    default: true
  },
  showTable: {
    type: Boolean,
    default: true
  },
  showFooter: {
    type: Boolean,
    default: true
  }
})

defineEmits(['upload-logo'])

const formatDate = (date: Date) => {
  return date.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })
}

const formatTime = (date: Date) => {
  return date.toLocaleTimeString('en-US', { 
    hour: '2-digit', 
    minute: '2-digit',
    hour12: true
  })
}
</script>

<style scoped>
.report-template {
  font-family: 'Inter', system-ui, -apple-system, sans-serif;
  line-height: 1.5;
}

/* Professional table styling */
.report-template :deep(table) {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}

.report-template :deep(thead) {
  background: #f9fafb;
  border-bottom: 2px solid #e5e7eb;
}

.report-template :deep(th) {
  padding: 12px;
  text-align: left;
  font-weight: 600;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #374151;
  border-bottom: 2px solid #d1d5db;
}

.report-template :deep(td) {
  padding: 12px;
  color: #111827;
  border-bottom: 1px solid #e5e7eb;
}

.report-template :deep(tbody tr:hover) {
  background: #f9fafb;
}

.report-template :deep(tbody tr:last-child td) {
  border-bottom: 2px solid #d1d5db;
}

/* Status badges */
.report-template :deep(.status-badge) {
  display: inline-block;
  padding: 4px 10px;
  border-radius: 9999px;
  font-size: 11px;
  font-weight: 500;
}

/* Print styles */
@media print {
  .report-template {
    print-color-adjust: exact;
    -webkit-print-color-adjust: exact;
  }
}
</style>
