<template>
  <div class="report-template bg-white min-h-[297mm] flex flex-col">
    <!-- Report Header -->
    <div v-if="showHeader" class="report-header border-b-2 border-gray-800 pb-4 mb-4">
      <div class="flex justify-between items-start">
        <div class="flex items-start gap-4 flex-1">
          <!-- Logo Area - Resizable -->
          <div 
            v-if="logoUrl" 
            :style="{ width: logoSize + 'px', height: logoSize + 'px' }"
            class="rounded-lg overflow-hidden flex items-center justify-center bg-white flex-shrink-0"
          >
            <img :src="logoUrl" alt="Company Logo" class="w-full h-full object-contain" />
          </div>
          <div 
            v-else
            :style="{ width: logoSize + 'px', height: logoSize + 'px' }"
            class="bg-blue-600 rounded-lg flex items-center justify-center cursor-pointer hover:bg-blue-700 transition-colors flex-shrink-0"
            @click="$emit('upload-logo')"
            title="Click to upload logo"
          >
            <svg class="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
            </svg>
          </div>
          <!-- Company Info beside logo -->
          <div class="flex-1">
            <h2 class="text-base font-bold text-gray-900">{{ companyName }}</h2>
            <p class="text-sm text-gray-600 mt-1 whitespace-pre-line">{{ companyAddress }}</p>
          </div>
        </div>
        <div class="text-right">
          <p class="text-xs text-gray-500 uppercase tracking-wide mb-1">Report Generated</p>
          <p class="text-sm font-semibold text-gray-900">{{ formatDate(generatedDate) }}</p>
          <p class="text-xs text-gray-600 mt-1">{{ formatTime(generatedDate) }}</p>
        </div>
      </div>
    </div>

    <!-- Report Title - Below header, above content -->
    <div v-if="showHeader" class="mb-4">
      <h1 class="text-2xl font-bold text-gray-900">{{ title }}</h1>
      <p v-if="subtitle" class="text-sm text-gray-600 mt-1">{{ subtitle }}</p>
    </div>

    <!-- Filters Applied Section (if any) -->
    <div v-if="appliedFilters.length > 0" class="mb-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
      <h3 class="text-xs font-semibold text-blue-900 uppercase tracking-wide mb-2">Filters Applied</h3>
      <div class="grid grid-cols-2 gap-x-6 gap-y-2">
        <div v-for="filter in appliedFilters" :key="filter.label" class="flex items-center gap-2">
          <span class="text-xs text-blue-700 font-medium">{{ filter.label }}:</span>
          <span class="text-xs text-blue-900">{{ filter.value }}</span>
        </div>
      </div>
    </div>

    <!-- Main Content Slot -->
    <div v-if="showTable" class="report-content">
      <slot></slot>
    </div>

    <!-- Report Footer -->
    <div v-if="showFooter" class="report-footer mt-auto pt-4 border-t border-gray-300">
      <div class="flex justify-between items-center text-xs text-gray-600">
        <div>
          <p class="font-semibold text-gray-900">{{ companyName }}</p>
        </div>
        <div class="text-right">
          <p>Generated by: <span class="font-medium text-gray-900">{{ currentUsername || generatedBy }}</span></p>
          <p class="mt-0.5">Page 1 of 1</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import axios from '@/utils/axios'

interface SummaryCard {
  label: string
  value: string | number
  subtitle?: string
}

interface AppliedFilter {
  label: string
  value: string
}

const props = defineProps({
  title: {
    type: String,
    required: true
  },
  subtitle: {
    type: String,
    default: ''
  },
  generatedDate: {
    type: Date,
    default: () => new Date()
  },
  appliedFilters: {
    type: Array as () => AppliedFilter[],
    default: () => []
  },
  summaryCards: {
    type: Array as () => SummaryCard[],
    default: () => []
  },
  companyName: {
    type: String,
    default: 'Warehouse Management System'
  },
  companyAddress: {
    type: String,
    default: 'Generated from WMS Platform'
  },
  generatedBy: {
    type: String,
    default: 'System Administrator'
  },
  logoUrl: {
    type: String,
    default: ''
  },
  logoSize: {
    type: Number,
    default: 80
  },
  showHeader: {
    type: Boolean,
    default: true
  },
  showTable: {
    type: Boolean,
    default: true
  },
  showFooter: {
    type: Boolean,
    default: true
  }
})

defineEmits(['upload-logo'])

const currentUsername = ref('')

const formatDate = (date: Date) => {
  return date.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })
}

const formatTime = (date: Date) => {
  return date.toLocaleTimeString('en-US', { 
    hour: '2-digit', 
    minute: '2-digit',
    hour12: true
  })
}

const fetchCurrentUser = async () => {
  try {
    const userStr = localStorage.getItem('user')
    if (userStr) {
      const user = JSON.parse(userStr)
      if (user.username) {
        currentUsername.value = user.username
      } else if (user.name) {
        currentUsername.value = user.name
      }
    }
  } catch (error) {
    console.error('Error fetching current user:', error)
  }
}

onMounted(() => {
  fetchCurrentUser()
})
</script>

<style scoped>
.report-template {
  font-family: 'Inter', system-ui, -apple-system, sans-serif;
  line-height: 1.5;
  min-height: 297mm; /* A4 height */
}

/* Professional table styling */
.report-template :deep(table) {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}

.report-template :deep(thead) {
  background: #f9fafb;
  border-bottom: 2px solid #e5e7eb;
}

.report-template :deep(th) {
  padding: 12px;
  text-align: left;
  font-weight: 600;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #374151;
  border-bottom: 2px solid #d1d5db;
}

.report-template :deep(td) {
  padding: 12px;
  color: #111827;
  border-bottom: 1px solid #e5e7eb;
}

.report-template :deep(tbody tr:hover) {
  background: #f9fafb;
}

.report-template :deep(tbody tr:last-child td) {
  border-bottom: 2px solid #d1d5db;
}

/* Status badges */
.report-template :deep(.status-badge) {
  display: inline-block;
  padding: 4px 10px;
  border-radius: 9999px;
  font-size: 11px;
  font-weight: 500;
}

/* Print styles */
@media print {
  .report-template {
    print-color-adjust: exact;
    -webkit-print-color-adjust: exact;
    min-height: 297mm;
  }
  
  .report-footer {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
  }
}
</style>
